export const checklistHeaderFI_json = {
  name: "checklist_header_fi",
  title: "Checklist FI Header",
  titleLocation: "hidden",
  hideNumber: true,
  elementsJSON: [
    {
      type: "text",
      name: "station",
      title: "Station",
      titleLocation: "left",
      width: "45%",
      isRequired: true,
    },
    {
      type: "text",
      name: "wo",
      title: "Work Order",
      titleLocation: "left",
      startWithNewLine: false,
      width: "45%",
      isRequired: true,
    },
    {
      type: "text",
      name: "toolid",
      title: "Tool ID",
      titleLocation: "left",
      width: "45%",
      isRequired: true,
    },
    {
      type: "text",
      inputType: "datetime-local",
      name: "date",
      title: "Date",
      titleLocation: "left",
      startWithNewLine: false,
      width: "45%",
      isRequired: true,
    },
  ],
};
