export const checklistHeaderShipKit_json = {
  name: "checklist_header_shipkit",
  title: "Checklist ShipKit Header",
  titleLocation: "hidden",
  hideNumber: true,
  elementsJSON: [
    {
      type: "text",
      name: "wo",
      title: "Work Order",
      titleLocation: "left",
      width: "30%",
      // startWithNewLine: false,
      isRequired: true,
    },
    {
      type: "text",
      name: "toolid",
      title: "Tool ID",
      titleLocation: "left",
      startWithNewLine: false,
      width: "30%",
      isRequired: true,
    },
    {
      type: "text",
      inputType: "datetime-local",
      defaultValueExpression: "currentDate()",
      name: "date",
      title: "Date",
      titleLocation: "left",
      width: "30%",
      startWithNewLine: false,
      isRequired: true,
    },
  ],
};
