// dc stands for datacollection
export const dc_predefined_json = {
  name: "datacollection_header",
  title: "Data Collection Header",
  titleLocation: "hidden",
  hideNumber: true,
  elementsJSON: [
    {
      type: "text",
      name: "wo",
      title: "WO",
      titleLocation: "left",
      maxWidth: "33%",
      minWidth: "33%",
      isRequired: true,
      isReadOnly: true,
    },
    {
      type: "text",
      name: "oms",
      title: "OMS",
      titleLocation: "left",
      isRequired: true,
      minWidth: "33%",
      maxWidth: "33%",
      startWithNewLine: false,
      isReadOnly: true,
    },
    {
      type: "text",
      name: "step",
      title: "Step",
      titleLocation: "left",
      isRequired: true,
      minWidth: "33%",
      maxWidth: "33%",
      startWithNewLine: false,
      isReadOnly: true,
    },
    {
      type: "text",
      name: "station",
      title: "Station",
      titleLocation: "left",
      isRequired: true,
      minWidth: "25%",
      maxWidth: "25%",
      isReadOnly: true,
    },
    {
      type: "text",
      name: "omssn",
      title: "OMS SN",
      titleLocation: "left",
      isRequired: true,
      minWidth: "20%",
      maxWidth: "20%",
      startWithNewLine: false,
      isReadOnly: true,
    },
    {
      type: "text",
      name: "plant_code",
      title: "Plant Code",
      titleLocation: "left",
      isRequired: true,
      minWidth: "20%",
      maxWidth: "20%",
      startWithNewLine: false,
      isReadOnly: true,
    },
    {
      type: "text",
      name: "userid",
      title: "User ID",
      titleLocation: "left",
      isRequired: true,
      minWidth: "35%",
      maxWidth: "35%",
      startWithNewLine: false,
      isReadOnly: true,
    },
  ],
};
