export interface ThemeOption {
    value: string;
    label: string;
}

export const themeOptions: ThemeOption[] = [
    { value: "0", label: "Default Light" },
    { value: "1", label: "Default Dark" },
    { value: "2", label: "Contrast Light" },
    { value: "3", label: "Contrast Dark" },
    { value: "4", label: "Borderless Dark Panelless" },
    { value: "5", label: "Borderless Dark" },
    { value: "6", label: "Borderless Light Panelless" },
    { value: "7", label: "Borderless Light" },
    { value: "8", label: "Contrast Dark Panelless" },
    { value: "9", label: "Contrast Light Panelless" },
    { value: "10", label: "Default Light Panelless" },
    { value: "11", label: "Double Border Dark Panelless" },
    { value: "12", label: "Double Border Dark" },
    { value: "13", label: "Double Border Light Panelless" },
    { value: "14", label: "Double Border Light" },
    { value: "15", label: "Flat Dark Panelless" },
    { value: "16", label: "Flat Dark" },
    { value: "17", label: "Flat Light Panelless" },
    { value: "18", label: "Flat Light" },
    { value: "19", label: "Layered Dark Panelless" },
    { value: "20", label: "Layered Dark" },
    { value: "21", label: "Layered Light Panelless" },
    { value: "22", label: "Layered Light" },
    { value: "23", label: "Plain Dark Panelless" },
    { value: "24", label: "Plain Dark" },
    { value: "25", label: "Plain Light Panelless" },
    { value: "26", label: "Plain Light" },
    { value: "27", label: "Sharp Dark Panelless" },
    { value: "28", label: "Sharp Dark" },
    { value: "29", label: "Sharp Light Panelless" },
    { value: "30", label: "Sharp Light" },
    { value: "31", label: "Solid Dark Panelless" },
    { value: "32", label: "Solid Dark" },
    { value: "33", label: "Solid Light Panelless" },
    { value: "34", label: "Solid Light" },
    { value: "35", label: "Three Dimensional Dark Panelless" },
    { value: "36", label: "Three Dimensional Dark" },
    { value: "37", label: "Three Dimensional Light Panelless" },
    { value: "38", label: "Three Dimensional Light" },
];
