# pull official base image
FROM node:16.20.2

# set working directory inside container
WORKDIR /uct-checklist/checklist-frontend

# install app dependencies
COPY package.json ./
RUN npm install --legacy-peer-deps

# add app source code
COPY . .

# optional: start server (留给 docker-compose 控制）

