name: Deploy debug uct-checklist

on:
  push:
    branches:
      - debug

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Trust /uct-checklist as a safe Git directory
        run: |
          git config --global --add safe.directory /uct-checklist

      - name: Deploy from mounted directory 
        run: |
          cd /uct-checklist
          git switch debug
          git pull origin debug
          docker compose -f docker-compose.dev.hotloading.yml down 
          docker compose -f docker-compose.dev.hotloading.yml up -d --build 
